worker_processes 1; # Strictly lock to 1 process for your single ARM core

events {
    worker_connections 1024;
    use epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Performance optimizations to protect the CPU
    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    types_hash_max_size 2048;

    # Hide Nginx version tokens for a bit of extra security
    server_tokens off;

    # Include all individual reverse proxy configs
    include /etc/nginx/conf.d/*.conf;
}
